### ISSUE TITLE
Undercover picking up changes from master and reporting false negative

### ISSUE THREAD

**Issue by hiralmodi22** [grodowski/undercover#67] opened 2019-08-07 22:48 UTC
I have a branch which implements undercover in our ci (buildkite) pipeline. I have added undercover as a step after all specs run. I see false negative results every now and then. The changes that undercover points out needs coverage are always things someone else on the team has merged to master recently. 

The command that I run is `undercover --lcov <file.lcov> --compare origin/master` 

Steps: 

- Create a branch and add all logic for undercover to work.(logic - Generate all lcov files in each ci container, aggregate them into one file which is passed as an argument to undercover command. Similar to what is described here - https://github.com/grodowski/undercover/blob/master/docs/circleci_advanced.yml )

- Push the branch to build on ci - it works fine so far. Undercover does not identify any non-covered changes

- Pull master into my branch and push branch to origin

- The ci build that was triggered shows bunch of methods as not covered. These are changes already on master, merged by team member recently. 

- The changes which undercover reports as uncovered are not part of what I am working on.

**Comment by grodowski** [comment] 2019-08-09 08:39
Hi! Thanks for using undercover and reporting the issue.

I couldn't reproduce your exact scenario based on the description, so I'd welcome more details. A sample git tree is one option.

However, I noticed a strange behaviour of `undercover -c master` when master has diverged from a feature branch with new commits. 

```
#  git log --graph test-untested master
* commit a00a293bb7c2284b0436de0c331f47f6f8761352 (HEAD -> master)
|
|     change #3
|
| *   commit bbe55cd3e0435861d0411c35c5d0c2307d7f3e8b (test-untested)
| |\  Merge: 0d8ee01 0279ca5
| |/  
|/|     Merge branch 'master' into test-untested
| |
* | commit 0279ca5d7a0ae2c1e6aa13d79708dd2dff4b9015
| |
| |     untested :o #2
| |
| * commit 0d8ee017d8c37ac6dba4efab6cae5151f61d831d
|/  
|       foo #1
|
*   commit a71309fa6e5f9465ec040f36b3f4f53e64b51824 (origin/master)
```

Change 3 is not included in the undercover changeset. Specifically:
- undercover would currently compare `bbe55cd3` with `a71309fa6`
- we'd expect it to compare `bbe55cd3` with `a00a293b`

Not sure if this relates to your problem, but I will take a deeper look and possibly change

https://github.com/grodowski/undercover/blob/a71309fa6e5f9465ec040f36b3f4f53e64b51824/lib/undercover/changeset.rb#L76

to something like

```
repo.branches.find { |b| b.name == compare_base }.target
```

This could be more predictable than `merge_base` in more complex workflows

FYI https://git-scm.com/docs/git-merge-base

**Comment by grodowski** [comment] 2019-08-26 21:23
@hiralmodi22 this could help with diff issues, please lmk if it does

**Comment by Redapted** [comment] 2019-09-04 19:24
@grodowski To simplify the branch illustration a bit;

```
(branch)       M - N - O - P
              /       /
(master) A - B - C - D - E - F
```

Briefly, we branched at `B`, and then ran `git merge master` at `D`.

So if we want to see what untested code blocks would be introduced by our branch, we would want to diff `P` vs `D`, correct? #68 causes us to diff `P` vs. `F`, which will include changes from `E` and `F`. The result is that Undercover would include irrelevant changes in its results.

Unless I'm missing something?

To get the correct commit to diff, I've been running `git merge-base master current-branch` locally, which looks like the same strategy as before #68. Granted, my workflows aren't quite as complex as in your example, so that may be a poor general-purpose solution. One suggestion, as a compromise, would be to have usage of `merge_base` vs `rev_parse` controlled via a command-line switch.

All that being said, I'm not totally sure what caused the original issue @hiralmodi22 was encountering. Could be a nuance of shallow clone? Git is more clever about that than it used to be, but could be a gap here.

**Comment by grodowski** [comment] 2019-09-10 19:40
Thanks for your comment @Redapted. I am not sure what caused the issue either and it would be cool to get more input from @hiralmodi22. 

Looking into the `rev-parse` versus `merge-base` question, I think it depends on the workflow we want undercover to best support. 

In your example, if all code changes went through review (including undercover) that used `merge-base`, we would be sure that all additions from `E` and `F` are covered and we could safely check `P` w.r.t. `D`.  On the other hand `rev-parse` could yield code locations that have been deleted or changed in `F`, but are still present in `P`, meaning they require tests if we merge `P` into `F`. Should we still call these false positives? I might as well be missing some obvious edge case here

There might be some confusion too, because undercover triggers on class, method and block diffs instead of individual lines.

Finally, #68 is still unreleased and I'm debating whether to just roll it back from `master`. Not sure if there's really that much benefit in using `rev-parse`.

**Comment by grodowski** [comment] 2019-10-02 16:10
I'm reverting #68 from master a closing this issue as not much has happened here.

**Closed by grodowski** 2019-10-02 16:10 UTC

**Comment by mkllnk** [comment] 2026-04-24 00:57
I saw a case were our CI run was reporting missing code coverage on code that had been removed in our master branch. It was completely unrelated to the tested pull request. I think that I can solve that by comparing to the pull request base instead of master.
```diff
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 33f3663f33..1d2d342993 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -410,6 +410,6 @@ jobs:
           include-hidden-files: true
       - name: Compare SimpleCov results with Undercover
         run: |
-          git fetch --no-tags origin ${{ github.event.pull_request.base.ref }}:master
+          git fetch --no-tags origin ${{ github.event.pull_request.base.sha }}:master
           bundle exec undercover
         if: ${{ github.ref != 'refs/heads/master' }} # Does not run on master, as we can't fetch master in the master branch
```

I thought that undercover was already comparing to the base but does that fail when we are on a merge commit like on Github Actions?

I'm just sharing that here in case it helps someone else. I don't have code to reproduce a bug.

**Comment by grodowski** [comment] 2026-04-25 05:31
Thanks for your comment @mkllnk! Does your action use a shallow checkout? 

`undercover` does try to resolve the merge base for `--compare` (in your example the `base.sha` is the merge base), but this can return `nil` when the commit chain is not available in the clone.  

I think it will be a sensible documentation update, also thought about printing a warning to `stderr` when the merge base lookup fails.

**Comment by mkllnk** [comment] 2026-04-27 00:34
> Does your action use a shallow checkout?

Yes and no. Github `actions/checkout` fetches shallow and then checks out the branch. One example:

```
git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +1967659526ec6eecf0a6ee1c05e7347301692a1a:refs/remotes/origin/taler-properties
git checkout --progress --force -B taler-properties refs/remotes/origin/taler-properties
```

But then we were fetching the master branch to enable the comparison:
```
git fetch --no-tags origin master:master
bundle exec undercover
```

After the fetch, all the commits are present and I can find the merge-base. So I'm not sure why undercover didn't find it in this case.

Most of the time, undercover's behaviour doesn't matter because we use the merge commit of the pull request and then compare with master which is already merged into HEAD. Just in this one case, there were additional commits in master because CI ran at the same time as someone was merging pull requests. If it happens again, I might try to reproduce it somehow.
